### ISSUE TITLE
EdgeInsets for Vertical and Horizonal Layout Methods Are Misleading

### ISSUE THREAD

**Issue by sroddy** [BendingSpoons/katana-swift#101]
As horizontal and vertical components of `EdgeInsets` are ignored when passed respectively to vertical and horizontal filling methods, we probably should consider adding VerticalEdgeInsets and HorizontalEdgeInsets types and use them as required types for these methods

**Comment by bolismauro** [comment]
I think it makes sense

**Comment by bolismauro** [comment]
Closed. Please re open it in the proper repo
