### ISSUE TITLE
undefined is not an object (evaluting 'Proptypes.number')

### ISSUE THREAD

**Issue by malangaveuday** [BendingSpoons/katana-swift#133]
![img-8569](https://user-images.githubusercontent.com/12609892/29167572-8f9efb40-7de8-11e7-8240-82347cbce4a5.PNG)
Error in react-native project.

**Comment by bolismauro** [comment]
are you using react native with katana?
Can you share more information? It is not clear which is the issue

**Comment by malangaveuday** [comment]
It's resolved.
