### ISSUE TITLE
Fail carthage build

### ISSUE THREAD

**Issue by ct4h** [BendingSpoons/katana-swift#137]
Run carthage command:

` bundle exec fastlane carthage_update:`

```
lane :update_carthage do
        carthage(
            platform: "iOS",
            cache_builds: true,
            use_binaries: false
        )
end
```

Project configuration:

language:  swift4
enable bitcode: true
enable code coverage: false

Build log: 

/usr/bin/xcrun xcodebuild -project /Users/mac/katana-example/Carthage/Checkouts/katana-swift/Katana.xcodeproj -scheme Katana\ iOS -configuration Release -derivedDataPath /Users/mac/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/katana-swift/0.8.12 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/mac/katana-example/Carthage/Checkouts/katana-swift)User defaults from command line:
    IDEArchivePathOverride = /Users/mac/katana-example/Carthage/Checkouts/katana-swift
    IDEDerivedDataPathOverride = /Users/mac/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/katana-swift/0.8.12

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos11.0
    SKIP_INSTALL = YES

xcodebuild: error: Scheme Katana iOS is not currently configured for the archive action.

**Comment by bolismauro** [comment]
Fixed
