### ISSUE TITLE
StoreListener change

### ISSUE THREAD

**Issue by AlfioRusso** [BendingSpoons/katana-swift#164]
# Problem
Right now `StoreListener`s do not have the capability to reason about diffs between old state and new state.
An example of usage could be change the `LocalState` of a `ViewController` in [Tempura](https://github.com/BendingSpoons/tempura-swift/tree/master) based on those differences inside [`func update(with state: V.VM.S)`](https://github.com/BendingSpoons/tempura-swift/blob/a5279c04fafcaff05f4f192c39570e9b7c7a8bb3/Tempura/Core/ViewController.swift#L285) that could become `func update(oldState: V.VM.S)`.

# Proposal
Modify `StoreListener` to accept the oldState as parameter, this should be fairly simple.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199108774605801/1199216872415402) by [Unito](https://www.unito.io/learn-more)

**Comment by LorDisturbia** [comment]
Bump

**Comment by bolismauro** [comment]
I think it is a good idea.
Do you have any idea on how to make this feature non-breaking?

**Comment by danyf90** [comment]
Released in 6.0.0
