### ISSUE TITLE
Provide Sample Project

### ISSUE THREAD

**Issue by hkellaway** [BendingSpoons/katana-swift#191]
In trying to understand Katana, I found myself seeking a sample project (independent of Tempura or Katana-UI) to better grasp how things fit together. Examples of `StateUpdater`, `SideEffect`, and `Interceptor` usage specifically. 

What would be above-and-beyond is a non-trivial demo that also incorporates the BPS Guidelines 😇

Great work, by the way!

**Comment by bolismauro** [comment]
Hi! You can find a medium-size app here https://github.com/immuni-app/immuni-app-ios. I hope it can help you understanding Katana better!
