### ISSUE TITLE
Add an example about wrapping Apple view controllers

### ISSUE THREAD

**Issue by bolismauro** [BendingSpoons/katana-swift#66]
In Bending Spoons we like to have our own version of most the UIKit's elements and Katana is very in line with this philosophy.

That said, this is not something we can ask to people that use Katana. In particular Apple provides a widely used view controllers that are used for navigation within iOS applications (e.g., TabBar, NavigationController, ...).

It is totally possible to wrap these view controllers in Katana descriptions and expose an interface to use them. We should provide an example for the community that acts as a starting point for this kind of situations. I suggest to use the navigation example since it is most likely the most common one.

Note that we have a fully declarative, Katana based solution for navigation, but we is not public (yet) because it is at the moment strongly tied to internal conventions and technologies. Moreover it doesn't really solve the problem of using UIKit view controllers, so it isn't a real solution to this issue.

**Comment by lucaquerella** [comment]
@olegam

**Comment by olegam** [comment]
Yay. Looking forward to see the demo of how this can be done 🎉

**Comment by bolismauro** [comment]
@olegam I was thinking to create this demo tomorrow but probably I can't do it since I need to give priority to other things..
I'll keep you posted

**Comment by bolismauro** [comment]
Closed. Please re open it in the proper repo
