### ISSUE TITLE
Change The Reference Size (e.g. According to Device Orientation)

### ISSUE THREAD

**Issue by sroddy** [BendingSpoons/katana-swift#67]
After taking a look at the various examples I'm having some problems finding a proper way to change the reference size of a Node.

A typical use case is when the device orientation changes. What we used to do in Plastic was to flip the x and y values of the reference size and change other (usually minor) details in the layout method.

Another use case is if we want to have two or more different layouts when using different devices (e.g. iPhone 4s/7/7plus, iPad/iPad Pro) or when you are in an environment where you can actively change the size of the rendered window (MacOS, multitasking iPad)

I see two ways to potentially fix the issue:
1. Implement a way to dynamically change the reference size.
2. Don't change the interface and assume that the reference size will invert it's values when the device orientation is in landscape mode.

My opinion:
Solution 2. would probably be enough to cover most use cases and I think it would be anyways a very good practice to enforce the developers to adopt it by default.

Solution 1. is to be able to define a set of different reference sizes during the Node initialization and have a mechanism that:
- automatically matches the closest one (first by ratio, then by size);
- makes it available in both the render and the layout methods in a way that is easily comparable using an if / switch;
- triggers a render/layout whenever the frame of the reference view changes.
- keeps the original way of providing just one size which will basically become a shorthand for providing two reference sizes (the provided one and the one with inverted x and y) that, as I said before, would probably cover most of the use cases.

**Comment by bolismauro** [comment]
I'm not sure that having a "magic" thing that pick the reference size according to an algorithm would be a good thing. 
We need to understand if this happens only for orientation (in this case we can simply provide different reference sizes, one for each orientation) or there are others use cases.

The layout logic differentiation according to the device (or something more abstract, like the Apple size classes) is not strictly related to the reference size: we need a way to specify different layout logics (maybe more methods?)

**Comment by sroddy** [comment]
Speaking of which (MacOS), I'm wondering how we would be currently able to layout things inside a window that have a size that can be arbitrarily changed by the user.
This makes me think that while with iOS devices we could be able to handle things in a relatively easy way, if we want to make it work for MacOS we will surely need something more powerful that is able to be truly responsive.

I'll think about a good approach that won't overcomplicate things and let you know soon.

Meanwhile suggestions and real-world use cases (especially for MacOS apps) are very welcome!

**Comment by bolismauro** [comment]
Closed. Please re open it in the proper repo
