### ISSUE TITLE
Node DSL

### ISSUE THREAD

**Issue by lucaquerella** [BendingSpoons/katana-swift#69]
Both @Danappelxx (here: https://m.reddit.com/r/swift/comments/5d98u4) and gavrocheBxN (here: https://www.reddit.com/r/reactnative/comments/5d9968/) mention that they would like to have a DSL to define the nodes (al la JSX).

While I don't think this is a priority I do believe this is possible and I'd like to hear other people's opinion on that.

**Comment by majorgilles** [comment]
If it can be type checked it could be an option... but vanilla swift is not unreadable and already has these qualities...

**Comment by bolismauro** [comment]
Closed. Please re open it in the proper repo
