### ISSUE TITLE
Reducers?

### ISSUE THREAD

**Issue by alexanderjarvis** [BendingSpoons/katana-swift#81]
I just have a simple question as I've been using Redux directly for the last few months:

Where are the Reducers?

It seems like you are putting all your state mutation code inside your actions. Is this a pattern that you adopted on purpose and if so then why?

**Comment by lucaquerella** [comment]
Hi @alexanderjarvis!

Katana is not a 1:1 translation of React and Redux, it's definitely inspired by them but not just a Swift remake. When we started the library, we challenged every single aspect of those library and we try to build a library that we believe is great to build Swift iOS (and soon macOS) apps :) - If you explore the code you'll notice many other differences. 

If you look the first commits you'll notice that at the beginning we had modelled the reducer (exactly as React does) later we decided to move that logic (and the sideEffects too) inside the actions. We believe that this refactor made the code of our apps much more clean and easy to read. Give it a try with an open mind and tell us what you think about it - I hope you'll like it :)

**Comment by bolismauro** [comment]
It's also worth to mention that while we have lost the power of the reducers a la redux (combine reducers for instance) we didn't really missed it because of two differences between swift and js:
- static type checking (of course you can have it in js too with flow or TS, but redux was born for js)
- use value types instead of reference types. Basically you don't really need to "create" the state every time. You can just update it, since the swift struct are copied by value

In general we felt that this solution was more in line with Swift characteristics. Plus it helped us avoiding a lot of boilerplate. And here we are not talking about being lazy. Having boilerplate in your code push people in bad practices and also in be less effective when you need to understand someone else code

As Luca said, please feel free to give your inputs :) we are open to discuss and potentially change every aspect of Katana

**Comment by alexanderjarvis** [comment]
@lucaquerella @bolismauro thanks for your replies, I guess it just didn't sink in that it was inspired by, rather than being a port :)

It's really interesting to do it this way, however I'd say that by doing so you're missing on the benefit of separation of concerns between a declarative action and something that then processes that action.

I think that's the key point from a design aspect that although it's kinda nice to save some boilerplate, you may end up putting too much in your actions.

Keep in mind that I'm just pointing this out from a perspective of knowing about other systems that deal with immutable logs (not just redux). It just seems alien to put the logic of how to process an event/action inside the action itself because (depending on the system you are building) you may wish to replay these actions to reducers/consumers that have updated logic.

It's great that you're questioning the assumptions of the design though. Keep up the good work!

**Comment by bolismauro** [comment]
Besides the location of the function that updates the state (reducer in redux, updateState here), the thing I see we miss is the ability to compose several functions that deal with different sub pieces of the state.

I don't get your point about `you may wish to replay these actions to reducers/consumers that have updated logic.`. You mean update the logic and trigger the actions again (like in the time travel)?

I think it is doable in this approach too (beside the problem of inject new Swift code of course).
The update state was, in fact, a static pure function. Just like the redux reducers. We moved it to an instance method just for convenience but nothing has really changed. The idea of having a pure reducer is still there, it is just in another form.

Btw, I agree that it seems weird if compared to other architectures with this approach

**Comment by palcalde** [comment]
The approach of dealing with the action inside the actions itself is good to avoid long switches in reducers. At the end the approach of Redux is to have actions trigger reducer's 'in cascade', each reducer has a switch to decide whether or not they modify it's piece of state for that action.

The bad side I see of having the mutation of the state inside the actions is that a single action can now touch multiple nodes of the data tree (when in redux each reducer touch only when specific peace of data). 

It's interesting your approach vs redux one tho!

**Comment by bolismauro** [comment]
The key point here is why redux uses this approach. We felt that it wasn't needed in Swift because of the static type checker. I guess it's always a tradeoff

**Comment by palcalde** [comment]
Btw, just found this stackoverflow response from redux creator that might be interesting for this topic: http://stackoverflow.com/questions/32461229/why-use-redux-over-facebook-flux

**Comment by bolismauro** [comment]
Very interesting. Thanks for sharing.
I think that reuse of functionalities (e.g., by creating proper functions) is possible anyway.

I guess we will discover whether this approach works well or not only by using Katana :)

**Comment by patchthecode** [comment]
@palcalde from that stackOverflow link, it seems that the reasons as to why they designed it that way goes a lot deeper than just type checking.

@bolismauro taking that into consideration, do you guys see any possible "issues" coming down the line using this approach? And if there is, I guessing this library will have alternate solutions since its not a 1:1 translation?

**Comment by bolismauro** [comment]
@patchthecode we are using this approach in our applications and it is working well so far. It is hard to predict it issues will arise in the future but what I can promise is that if either us or the community will find major downsides about this approach, we will work on find a solution. I just don't want to introduce changes based on gut feelings.

By the way (and I'm not saying this is a good approach) it is possible to use the redux approach even in the current version of Katana, although it seems a little bit hackish to me (please tell me what you think):
(warning: code not tested)
```swift
protocol ExternalReducer: Action {
  var reducer: (_ state: State, _ action: Action) -> State
}
extension ExternalReducer {
 func updateState(state: State) {
   self.reducer(state: State, action: Action)
 }
}

func rootReducer(state: State, action: Action) -> State {
  return ApplicationState(
    piece1: reducerPiece1(state, action),
    ....
    pieceN: reducerPieceN(state, action),
  )
}

// convenience protocol
protocol AppExternalReducer: ExternalReducer {}
extension AppExternalReducer {
  var reducer: (_ state: State, _ action: Action) -> State {
    return rootReducer
  }
}

struct MyAction: AppExternalReducer {
  // only the payload here
}

```

**Comment by patchthecode** [comment]
@bolismauro Hey i'm not saying that you should change your approach. I actually like that you guys have decided to go your own route. 

Because I like this library, I'm just hoping that it also handles possible "issues" **(and i say possible because like you said, only when more people use the lib,  then we can actually see if they really *are* issues)**  that other libraries have handled.

**Comment by bolismauro** [comment]
Ah ok :)
As I said so far it worked well, let's see what happens

**Comment by patchthecode** [comment]
cool.

**Comment by palcalde** [comment]
@bolismauro I see that with 'Protocol Extensions' you can unify the behavior of your actions so all of them implement the same pattern: 

1) have updateState(state) call reducer(state, action) via ExternalReducer
2) have reducer(state, action) call rootReducer(state, action) via AppExternalReducer
3) have rootReducer return a fresh new state generated by using all reducers

I do agree with you that it looks a little bit hacky to implement all those protocol extensions to be able to reuse reducers easily. The main difference I see is that Redux conventions pushes you to reuse reducers via reducer composition while Katana Conventions, even tho you can surely do it with Protocols, makes it a little bit harder.

Anyway, thanks @bolismauro! is great to have this open minded discussion about frameworks with the people that actually do them. Keep the great work.

**Comment by bolismauro** [comment]
Alright, I think we have exhausted the topic :)
Fill free to reopen the issue for further discussions!
