### ISSUE TITLE
Elements are not correctly reused

### ISSUE THREAD

**Issue by bolismauro** [BendingSpoons/katana-swift#96]
I have the feeling that sometimes elements are not reused when they should.
For instance Textfields do not maintain the focus when the state is changed

**Comment by sroddy** [comment]
I'm not sure about this feeling, but I had a similar problem with the Textfield that could be somehow related to this issue:
I've discovered that all firstResponders inside a table/collection are reset whenever reloadData is hit. As the default implementation of the equals() inside the TableDelegate protocol always returns true, if you have a Textfield inside the Table, this method is invoked and the keyboard dismissed on every state change.

**Comment by bolismauro** [comment]
Uhmmm If reload data is triggered it makes sense that the keyboard is dismissed. But the reload should never happen if the delegate returns true. Can you check it is correctly invoked?

In general we should drop the reloaddata method because it is inefficient and causes this issues

**Comment by sroddy** [comment]
Yes, I can confirm that giving a right implementation to the equals() methods on the delegate and making it return true doesn't trigger the reloadData method and doesn't cause this behavior

**Comment by bolismauro** [comment]
alright then it is "normal".
We should improve the table as discussed in #51
